version: '3'
services:
 app:
    container_name: app
    build:
        context: ./docker/app
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - ./backend:/var/www/html/backend
        - ./frontend:/var/www/html/frontend
    links:
        - db
    ports:
        - 9000:9000
 web:
    container_name: web
    build:
        context: ./docker/web
        dockerfile: Dockerfile
    ports:
        - 80:80
        - 443:443
    depends_on:
        - app
    volumes:
        - ./docker/web/nginx.conf:/etc/nginx/conf/nginx.conf
        - ./docker/web/server.conf:/etc/nginx/conf.d/default.conf
        - ./docker/web/fastcgi.conf:/etc/nginx/conf.d/fastcgi.conf
    links:
        - app
 db:
    container_name: db
    build:
        context: ./docker/db
        dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root     #ここにroot用のパスワードを記載
      MYSQL_DATABASE: default        #ここにデータベースを記載
      MYSQL_USER: default           #ここにユーザ名を記載
      MYSQL_PASSWORD: secret      #ここにユーザ用パスワードを記載